name: Publish to GitHub Container Registry

on:
  push:
    branches: [edge]

jobs:
  recycle:
    runs-on: ubuntu-latest
    steps:
      - uses: chipkent/action-cleanup-package@v1.0.1
        continue-on-error: true
        with:
          github-token: ${{ secrets.GH_PAT }}
          package-name: thijmengthn/swaparr
          tag: edge
  publish:
    runs-on: self-hosted
    needs: recycle
    steps:
      - id: vtags
        run: echo ::set-output name=VTAG::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/thijmengthn/swaparr:edge
          platforms: linux/amd64,linux/arm64
          cache-to: type=gha,mode=max
          cache-from: type=gha
