name: Publish to GitHub Container Registry

on:
  push:
    branches: [edge]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Recycle edge tag
        uses: chipkent/action-cleanup-package@v1.0.1
        continue-on-error: true
        with:
          github-token: ${{ secrets.GH_PAT }}
          package-name: thijmengthn/swaparr
          tag: edge

      - name: Build and push to GHCR
        run: |
          echo ${{ secrets.GH_PAT }} | docker login --username thijmengthn --password-stdin ghcr.io
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/thijmengthn/swaparr:edge .
