name: Publish to GitHub Container Registry

on:
  push:
    branches: [edge]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: |
          docker login --username thijmengthn --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/thijmengthn/swaparr:edge
          docker push ghcr.io/thijmengthn/swaparr:edge
