name: Publish to GitHub Container Registry

on:
  push:
    branches: [edge]

env:
  REGISTRY_IMAGE: ghcr.io/thijmengthn/swaparr

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}

      - name: Build and push to GHCR
        run: |
          echo ${{ secrets.GH_PAT }} | docker login --username thijmengthn --password-stdin ghcr.io
          docker buildx build --push \
            --platform ${{ matrix.platform }}\
            --tag ghcr.io/thijmengthn/swaparr:edge .