name: Publish to GitHub Container Registry

on:
  push:
    branches: [edge]

jobs:
  recycle:
    runs-on: ubuntu-latest
    steps:
      - uses: chipkent/action-cleanup-package@v1.0.1
        continue-on-error: true
        with:
          github-token: ${{ secrets.GH_PAT }}
          package-name: thijmengthn/swaparr
          tag: edge
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}
      - name: Build and publish to GHCR
        run: |
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/thijmengthn/swaparr:edge .
