name: Publish to GitHub Container Registry

on:
  push:
    branches: [edge]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/${{ matrix.platform }}
          tags: ghcr.io/thijmengthn/swaparr:edge-${{ matrix.platform }}

  merge:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}
      - run: |
          docker buildx imagetools create --append \
            --tag ghcr.io/thijmengthn/swaparr:edge \
            ghcr.io/thijmengthn/swaparr:edge-arm64 \
            ghcr.io/thijmengthn/swaparr:edge-amd64
