name: Publish to GitHub Container Registry

on:
  push:
    tags: 
      - "*"

jobs:
  publish:
    name: Publish Latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/thijmengthn/swaparr:latest
            ghcr.io/thijmengthn/swaparr:${{ github.ref_name }}
