name: Publish to GitHub Container Registry

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Dockerfile
        run: |
          echo ${{ secrets.GH_PAT }} | docker login --username thijmengthn --password-stdin ghcr.io
          docker buildx build . \
            --tag swaparr:latest \
            --tag swaparr:${{ steps.get_version.outputs.VERSION }} \
            --platform linux/amd64,linux/arm64 \
            --label "org.opencontainers.image.licenses=MIT" \
            --label "org.opencontainers.image.source=https://github.com/thijmengthn/swaparr" \
            --label "org.opencontainers.image.description=This image of Swaparr is based on 'main', the stable release branch."

      - id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Push build to GHCR
        run: | 
          docker push ghcr.io/thijmengthn/swaparr:latest
          docker push ghcr.io/thijmengthn/swaparr:${{ steps.get_version.outputs.VERSION }}
