name: Publish to GitHub Container Registry

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}
      - name: Build and publish to GHCR
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/thijmengthn/swaparr:latest \
            --tag ghcr.io/thijmengthn/swaparr:${{ steps.image_tag.outputs.VERSION }} .
