name: Publish to GitHub Container Registry

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - id: vtags
        run: echo ::set-output name=VTAG::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thijmengthn
          password: ${{ secrets.GH_PAT }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/thijmengthn/swaparr:latest,ghcr.io/thijmengthn/swaparr:${{ steps.vtags.outputs.VTAG }}
          platforms: linux/amd64,linux/arm64
          cache-to: type=gha,mode=max
          cache-from: type=gha
