name: Publish to GitHub Container Registry

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Obtain image tag
        id: image_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build and push to GHCR
        run: |
          echo ${{ secrets.GH_PAT }} | docker login --username thijmengthn --password-stdin ghcr.io
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/thijmengthn/swaparr:latest \
            --tag ghcr.io/thijmengthn/swaparr:${{ steps.image_tag.outputs.VERSION }} .
